import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  Widget TextWidget(String text) {
    return Container(
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: TextButton(
          onPressed: () {

          },
          child: Text(
            text,
            style: Theme
                .of(context)
                .textTheme
                .bodyText1,
          ),
        ));
  }



  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery
        .of(context)
        .size;
    Widget DotWidget() {
      return Visibility(
        visible: size.width>1000? true:false,
        child: Container(child: Column(
          children: [
            Container(
              margin: const EdgeInsets.symmetric(vertical: 5),
              child: Row(children: [
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
              ],),
            ),
            Container(
              margin: const EdgeInsets.symmetric(vertical: 5),
              child: Row(children: [
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
              ],),
            ),
            Container(
              margin: const EdgeInsets.symmetric(vertical: 5),
              child: Row(children: [
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
              ],),
            ),
            Container(
              margin: const EdgeInsets.symmetric(vertical: 5),
              child: Row(children: [
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
              ],),
            ),
            Container(
              margin: const EdgeInsets.symmetric(vertical: 5),
              child: Row(children: [
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
              ],),
            ),
            Container(
              margin: const EdgeInsets.symmetric(vertical: 5),
              child: Row(children: [
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
                Container(width: 4, height: 4,
                  margin: const EdgeInsets.symmetric(horizontal: 5),
                  decoration: const BoxDecoration(color: Color(0xffEEEEEE),
                      shape: BoxShape.circle),),
              ],),
            ),
          ],
        ),),
      );
    }


    Widget AppBarWidget(){
      return Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Container(
            margin: const EdgeInsets.only(left: 30),
            child: Row(
              children: [
                Image.asset("assets/images/logo.png",width: 150,height: 150,),

                const  SizedBox(width: 10,),
                DotWidget()

              ],
            ),
          ),
          Container(
            margin: const EdgeInsets.only(top: 50),
            child: Row(
              children: [
                const SizedBox(
                    child: Icon(
                      Icons.search,
                      color: Color(0xff020202),
                    )),
                const SizedBox(width: 40,),
                TextWidget("Home"),
                TextWidget("Services"),
                TextWidget("About Us"),
                TextWidget("Blog"),
                const SizedBox(width: 40,),
              ],
            ),
          )
        ],
      );
    }

    Widget leftsideWidget(){
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text("Handmade,",style: Theme.of(context).textTheme.headline1,),
              Text("with an Extra",style: Theme.of(context).textTheme.headline1,),
              Text("Pinch of Love",style: Theme.of(context).textTheme.headline1,),
              const SizedBox(height: 15,),
              Text("We prepare out breads daily and that's where the\ncharming smell comes from.",style: Theme.of(context).textTheme.subtitle1,),
              const SizedBox(height: 50,),
              Row(
                children: [
                  Text("Get Info",style: Theme.of(context).textTheme.bodyText1,),
                  const SizedBox(width: 10,),
                  const  Icon(Icons.arrow_forward_outlined,color: Color(0xff020202),),
                  const SizedBox(width: 40,),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10,vertical: 10),
                    decoration:const BoxDecoration(
                        color: Color(0xff020202),
                        borderRadius: BorderRadius.all(Radius.circular(30))
                    ),
                    child: Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10,vertical: 10),
                          decoration:BoxDecoration(
                              color: Color(0xffc84042),
                              shape: BoxShape.circle,
                              border: Border.all(color: Colors.white)
                          ),
                          child: Icon(Icons.badge,color: Colors.white,),
                        ),
                        const SizedBox(width: 20,),
                        const  Text("Online Shop",style: TextStyle(color: Colors.white,fontWeight: FontWeight.w900,fontSize: 20),),
                        const SizedBox(width: 10,),
                      ],
                    ),
                  )
                ],)

            ],),
          
          
          Image.asset("assets/images/brad.png")
        ],
      );
    }

    return Scaffold(
      body: SizedBox(
        width: size.width,
        height: size.height,
        child: ListView(
          children: [
            AppBarWidget(),

            SizedBox( width: size.width,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
              Container(width: size.width *0.45,
              padding: const EdgeInsets.only(left: 80,top: 5),
              child: leftsideWidget(),
              ),
              Container(width: size.width *0.45,height: size.height*0.78,color: Colors.blue),
            ],),)
          ],
        ),
      ),
    );
  }
}
